import type { CollectionConfig } from 'payload'

import { hasRole } from './access'

export const Skins: CollectionConfig = {
  slug: 'skins',
  admin: { hidden: true, useAsTitle: 'title', defaultColumns: ['title', 'status', 'targets', 'updatedAt'] },
  versions: { drafts: true, maxPerDoc: 20 },
  access: {
    read: ({ req }) => req.user ? true : { status: { equals: 'published' } },
    create: hasRole(['admin', 'editor']),
    update: hasRole(['admin', 'editor', 'reviewer']),
    delete: hasRole(['admin']),
  },
  fields: [
    { name: 'title', type: 'text', required: true },
    { name: 'slug', type: 'text', required: true, unique: true },
    { name: 'summary', type: 'textarea', required: true, maxLength: 180 },
    { name: 'description', type: 'richText' },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: ['draft', 'pending_review', 'published', 'rejected', 'archived'],
    },
    {
      name: 'packageKind',
      type: 'select',
      required: true,
      defaultValue: 'theme',
      options: ['theme', 'paired'],
    },
    {
      name: 'targets',
      type: 'select',
      hasMany: true,
      required: true,
      options: [
        { label: 'Codex', value: 'codex' },
        { label: 'ChatGPT Desktop', value: 'chatgpt' },
      ],
    },
    {
      name: 'categories',
      type: 'select',
      hasMany: true,
      options: ['anime-2d', 'cyber-ui', 'editorial', 'minimal', 'cozy', 'mystic'],
    },
    {
      name: 'palette',
      type: 'select',
      hasMany: true,
      options: ['blue', 'cyan', 'green', 'orange', 'paper', 'mixed'],
    },
    { name: 'version', type: 'text', required: true },
    { name: 'hero', type: 'upload', relationTo: 'media', required: true },
    { name: 'logo', type: 'upload', relationTo: 'media' },
    { name: 'polaroid', type: 'upload', relationTo: 'media' },
    { name: 'package', type: 'relationship', relationTo: 'theme-packages', required: true },
    { name: 'petId', type: 'text' },
    { name: 'petDisplayName', type: 'text' },
    { name: 'petContractVersion', type: 'text' },
    { name: 'authorDisplayName', type: 'text' },
    { name: 'art', type: 'select', options: ['arcana', 'oxide', 'green', 'miku', 'paper'], defaultValue: 'paper' },
    { name: 'sourceType', type: 'select', options: ['manual', 'github'], defaultValue: 'manual' },
    { name: 'sourceUrl', type: 'text' },
    { name: 'license', type: 'text' },
    { name: 'downloads', type: 'number', defaultValue: 0, min: 0 },
    { name: 'reviewNote', type: 'textarea' },
    { name: 'reviewedBy', type: 'relationship', relationTo: 'users' },
    { name: 'reviewedAt', type: 'date' },
    { name: 'publishedAt', type: 'date' },
    { name: 'rejectionReason', type: 'textarea' },
  ],
}
