import Link from 'next/link'

import { PublicWorkspace } from '@/components/PublicWorkspace'
import { SkinCard } from '@/components/SkinCard'
import { listPublicSkins } from '@/lib/skins/catalog'

type SearchParams = Promise<Record<string, string | string[] | undefined>>

export default async function SkinsPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams
  const value = (key: string) => typeof params[key] === 'string' ? params[key] : undefined
  const skins = await listPublicSkins({ q: value('q'), target: value('target'), category: value('category'), sort: value('sort') })
  return <PublicWorkspace current="index"><section className="screen workbench-screen screen-search is-visible"><div className="search-head"><div><div className="kicker">THE INDEX / {String(skins.length).padStart(2, '0')} DESKTOP THEMES</div><h1>Find your<br /><em>work rhythm.</em></h1></div><form className="search-input" action="/skins"><span>⌕</span><input name="q" defaultValue={value('q')} placeholder="Search Codex + ChatGPT themes" /><kbd>⌘ K</kbd></form></div><div className="search-layout"><aside className="filter-rail"><div className="filter-title">FILTERS <Link href="/skins">Clear</Link></div><div className="filter-group"><span>Desktop target</span><Link className={!value('target') || value('target') === 'both' ? 'filter-option is-selected' : 'filter-option'} href="/skins">Codex + ChatGPT</Link><Link className={value('target') === 'codex' ? 'filter-option is-selected' : 'filter-option'} href="/skins?target=codex">Codex</Link><Link className={value('target') === 'chatgpt' ? 'filter-option is-selected' : 'filter-option'} href="/skins?target=chatgpt">ChatGPT</Link></div><div className="filter-group"><span>Character</span><Link className={value('category') === 'anime-2d' ? 'filter-option is-selected' : 'filter-option'} href="/skins?category=anime-2d">Anime / 2D</Link><Link className={value('category') === 'cyber-ui' ? 'filter-option is-selected' : 'filter-option'} href="/skins?category=cyber-ui">Cyber / UI</Link><Link className={value('category') === 'editorial' ? 'filter-option is-selected' : 'filter-option'} href="/skins?category=editorial">Editorial</Link><Link className={value('category') === 'minimal' ? 'filter-option is-selected' : 'filter-option'} href="/skins?category=minimal">Minimal</Link></div><div className="filter-group"><span>Sort</span><Link className={value('sort') === 'downloads' ? 'filter-option is-selected' : 'filter-option'} href="/skins?sort=downloads">Most downloaded</Link><Link className={!value('sort') || value('sort') === 'recent' ? 'filter-option is-selected' : 'filter-option'} href="/skins">Most recent</Link></div></aside><div className="search-results"><div className="results-toolbar"><span>{String(skins.length).padStart(2, '0')} results</span><span>Flow / 03 columns</span></div><div className="result-grid">{skins.map((skin) => <SkinCard key={skin.slug} skin={skin} />)}</div>{skins.length === 0 && <div className="empty-state">No published themes match this search. Try a wider query.</div>}</div></div></section></PublicWorkspace>
}
